name: Java CI with Gradle

on:
  push:
    branches:
      - main  # або інша гілка, яку хочеш використовувати

jobs:
  build:
    runs-on: ubuntu-latest  # Вибір операційної системи для запуску

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2  # Крок для клону репозиторію

      - name: Set up JDK 17
        uses: actions/setup-java@v2  # Встановлення JDK
        with:
          java-version: '17'  # Вказуємо версію JDK
          distribution: 'temurin'  # Вибір дистрибутива JDK

      - name: Give execute permission to gradlew
        run: chmod +x gradlew  # Додаємо права на виконання для gradlew

      - name: Build with Gradle
        run: ./gradlew build  # Команда для зборки проекту
